{% set name = "semchunk" %}
{% set version = "4.1.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/semchunk-{{ version }}.tar.gz
  sha256: f27dc85716a0e9509a3f99c78b961cc476b3120efe711ee9a9a950ed1bd0f8ba

build:
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - hatchling
    - pip
  run:
    - python
    - tqdm
    - dill  # [win]

test:
  source_files:
    - tests
  imports:
    - semchunk
  commands:
    - pip check
    - pytest -vv tests
  requires:
    - pip
    - pytest
    - tiktoken >=0.9.0
    - nltk >=3.9.1
    - transformers >=4.52.4

about:
  summary: A fast, lightweight and easy-to-use Python library for splitting text into semantically meaningful chunks.
  description: semchunk by Isaacus is a fast, lightweight and easy-to-use Python library for splitting text into semantically meaningful chunks.
  home: https://github.com/isaacus-dev/semchunk
  license: MIT
  license_file: LICENCE
  license_family: MIT
  doc_url: https://github.com/isaacus-dev/semchunk
  dev_url: https://github.com/isaacus-dev/semchunk

extra:
  recipe-maintainers:
    - umarbutler
    - dominictarro
